# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Cache-Mmap
version:      0.09
version_from: Mmap.pm
installdirs:  site
requires:
    Carp:                          0
    Fcntl:                         0
    Storable:                      0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
