--- #YAML:1.0
name:                Cache-Mmap
version:             0.10
abstract:            Shared cache using mmap'd file
license:             ~
author:              
    - Peter Haworth (pmh@edison.ioppublishing.com)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    Fcntl:                         0
    Storable:                      0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
